# Generated by Django 4.1 on 2022-12-19 17:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100000, 'Стоимость мебели не должна превышать 100тыс руб'), django.core.validators.MinValueValidator(500, 'Стоимость мебели не может быть ниже 500 руб')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furnitures', to=settings.AUTH_USER_MODEL)),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='furniture.furnituretype')),
            ],
        ),
    ]
