# Generated by Django 4.1 on 2023-02-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_furniture_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
